### ISSUE TITLE
provided i3status.conf not working by default

### ISSUE THREAD

**Issue by sfcal** [calvous/Surface-Fakedev#4]
An immediate copy paste of your i3 config battery settings results in `Error: status_command process exited unexpectedly (exit 1)`

**Comment by calvous** [comment]
Where did you copy it into? It must be the file i3status.conf. Find it in /etc/i3status.conf. And get rid of the "<-----------" thing. It is only to mark the change in the description. Pls do not copy and paste the entire thing. Just modify the entry there. Keep in mind that this is the configuration of the Manjaro i3 edition. Check in your config file where that points to in the bar {...} code block

**Comment by sfcal** [comment]
Ended up being my fault, just a typo in my path name.

However, I've had to change your icons as they don't appear correctly.

**Comment by calvous** [comment]
I think the icons are taken from the font installed for the status bar. This is in my bar{} code clock of the config file
```
font xft:URWGothic-Book 14
```
This shows me a battery when discharging and a lightning bolt when charging.
