### ISSUE TITLE
Battery-Monitor plus FakeDev

### ISSUE THREAD

**Issue by Catley94** [calvous/Surface-Fakedev#5]
(Current setup: Surface book 2 13", Linux Mint v19 Tara - Will be installing Ubuntu in the next couple of weeks) 
Hey, So I followed your instructions but I can't get it to work with Battery-Monitor unless you have a suggestion on another app?

When I run the uevents such as :
sudo ./power-status.py bat1.uevent # battery one

I do get the results, for the APT, BAT1 and BAT2, but when I open in Battery-Monitor (https://github.com/maateen/battery-monitor) I don't know where to add the config for Battery-Monitor so it can tell me my battery in a gui.

I'm sure it's me!!!! Any suggestions other than a knock on the head? :)

**Comment by calvous** [comment]
Your linked programm takes it's input from
```
acpi -b
```
This does not work on our Surface and this is why we have this workaround here until we get the kernel module.
Get the one for gnome i have linked in the readme.

**Comment by Catley94** [comment]
Unfortunately that's still not working. I don't have the battery icon in the top taskbar. :(

**Comment by calvous** [comment]
It probably depends on the DE you are running. I thought Mate or Cinnamon would be still compatible with gnome-shell extensions. I have never used Gnome so I will not much of help here.
